[package]
name = "sow-dist"
version = "0.1.0"
edition = "2024"
description = "Shadows of War — Unified build & deploy orchestrator"
license = "AGPL-3.0-only"

[[bin]]
name = "sow"
path = "src/main.rs"

[dependencies]
anyhow = "1"
base64 = "0.22"
brotli = { workspace = true }
minifier = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"
rand = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
walkdir = "2"
wasm-bindgen-cli-support = { workspace = true }
tempfile = { workspace = true }
sow-i18n = { workspace = true }
sow-core = { workspace = true }
sow-map = { workspace = true, features = ["generator"] }
