[package]
name = "sow-native"
version = "0.1.0"
description = "Shadows of War desktop shell"
authors = ["World of Unreal"]
license = "AGPL-3.0-or-later"
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[workspace]
