[package]
name = "sow-render"
version = "0.1.0"
edition = "2024"
description = "Shadows of War — pure GPU rendering pipelines and shaders"
license = "AGPL-3.0-only"

[dependencies]
blade-graphics = { git = "https://github.com/ohsalmeron/blade", rev = "be2fc3130ce09212f41a31bbce629f0a1c14bc61" }
blade-macros = { git = "https://github.com/ohsalmeron/blade", rev = "be2fc3130ce09212f41a31bbce629f0a1c14bc61" }
bytemuck = { workspace = true }
raw-window-handle = { workspace = true }
sow-data = { workspace = true }
sow-core = { workspace = true }
web-time = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
