[package]
name = "sow-map"
version = "0.1.0"
edition = "2024"
description = "Shadows of War Map Generator"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = ["generator", "osm"]
generator = ["dep:image", "dep:brotli"]
osm = [
    "generator",
    "dep:ehttp",
    "dep:reqwest",
    "dep:tokio",
    "dep:serde",
    "dep:serde_json",
]

[dependencies]
sow-core = { workspace = true }
log = { workspace = true }
bincode.workspace = true
crossbeam-channel = { workspace = true }
web-time = { workspace = true }

image = { workspace = true, optional = true }
brotli = { workspace = true, optional = true }
ehttp = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["rt", "rt-multi-thread"] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
