// @generated by sow-tools pack-building-atlas; do not edit.
pub(crate) const ATLAS_WIDTH: u32 = 136;
pub(crate) const ATLAS_HEIGHT: u32 = 136;
pub(crate) fn uv_rect(kind: sow_core::game::BuildingKind, level: u8) -> Option<[f32; 4]> {
    let Some([x, y, width, height]) = (match (kind, level.max(1)) {
        (sow_core::game::BuildingKind::Farm, 1) => Some([2, 2, 64, 64]),
        (sow_core::game::BuildingKind::Farm, 2) => Some([70, 2, 64, 64]),
        (sow_core::game::BuildingKind::Farm, 3) => Some([2, 70, 64, 64]),
        _ => None,
    }) else {
        return None;
    };
    Some([
        x as f32 / ATLAS_WIDTH as f32,
        y as f32 / ATLAS_HEIGHT as f32,
        (x + width) as f32 / ATLAS_WIDTH as f32,
        (y + height) as f32 / ATLAS_HEIGHT as f32,
    ])
}
