[package]
name = "sow-client"
version.workspace = true
edition = "2024"
description = "Shadows of War — main game client (simulation host, event loop, platform integrations)"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = []
dev = []

[dependencies]
sow-audio = { workspace = true }
sow-core = { workspace = true }
sow-data = { workspace = true }
sow-render = { workspace = true }
sow-i18n = { workspace = true }
sow-net = { workspace = true }
log = { workspace = true }
winit = { workspace = true }
bincode.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
brotli = { workspace = true }
ehttp = { workspace = true, features = ["streaming"] }
crossbeam-channel = { workspace = true }
web-time = { workspace = true }
image = { workspace = true }
url = { workspace = true }
blade-graphics = { git = "https://github.com/ohsalmeron/blade", rev = "be2fc3130ce09212f41a31bbce629f0a1c14bc61" }
blade-macros = { git = "https://github.com/ohsalmeron/blade", rev = "be2fc3130ce09212f41a31bbce629f0a1c14bc61" }
bytemuck = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { workspace = true }
wasm-bindgen = { workspace = true }
getrandom = { workspace = true, features = ["js"] }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
web-sys = { workspace = true, features = ["Window", "Document", "HtmlDocument", "Element", "HtmlElement", "HtmlInputElement", "HtmlAnchorElement", "HtmlCanvasElement", "Navigator", "Clipboard", "CssStyleDeclaration", "Node", "VisibilityState", "Location", "BinaryType", "Worker", "MessageEvent", "Storage", "MediaQueryList", "Blob", "Url", "BlobPropertyBag", "VisualViewport", "Event"] }
js-sys = { workspace = true }
